### ISSUE TITLE
Unable to compile the project.

### ISSUE THREAD

**Issue by nmahale10** [cankurtan/WebAppFromQtDesigner#1]
I am unable to compile this project may be because of some proxy settings.
can u pls tel me what to update n how.

**Comment by cankurtan** [comment]
Sorry for late response. Can you explain your problem in detail? I think it cannot be related with proxy settings. Simply, you can import project into your Eclipse(or another IDE) and run the program. Compiling from command line is a little bit sticky way to do it.

**Comment by nmahale10** [comment]
Hi..
  I am trying to run from Command Prompt as well as from IDE.
I am able to compile it but not able to RUN it.
Getting error as

"java.lang.NoClassDefFoundError: main/document/MyHTMLDocumentImpl
	at main.parse.QtUiFileParser.parse(QtUiFileParser.java:47)
	at main.WebApplicationView.main(WebApplicationView.java:62)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at edu.rice.cs.drjava.model.compiler.JavacCompiler.runCommand(JavacCompiler.java:267)
> "

Kindly Support

**Comment by m0d00ku** [comment]
This is exactly what i need to convert my QT Designer UI's to html.  I too am having issues.  I can't even compile the code from command line nor Sublime Text editor.  I downloaded your zip file and installed the latest JDK to use.
:
WebApplicationView.java:15: error: package main.parse does not exist
import main.parse.QtUiFileParser;
                 ^
WebApplicationView.java:57: error: cannot find symbol
                        QtUiFileParser uiParser = new QtUiFileParser();
                        ^
  symbol:   class QtUiFileParser
  location: class WebApplicationView
WebApplicationView.java:57: error: cannot find symbol
                        QtUiFileParser uiParser = new QtUiFileParser();
                                                      ^
  symbol:   class QtUiFileParser
  location: class WebApplicationView
3 errors

**Comment by Delphi251189** [comment]
This is exactly what i need, but unfortunly I have no expierence of java and have no idea how to compile this src.
1. Have anybody precompiled binary of this app? 
2. Have anybody successfuly compiled this app and may be can provide instructions.
3. Is there anybody know or may be tested is Signal-Slot connections defined on ui file works?
 for example if I have QStackedWidget with 5 widgets and QComboBox with 5 items. I can connect currentIndexChanged(int) Signal of QComboBox to setCurrentIndex(int) slot of QStackWidget directly in ui file (not in *.cpp ). Most likely this app will generate somthing like javascript code  somwhere in html, somthing equivalent of Qt's analog concept. So it or not?

**Comment by cankurtan** [comment]
Dear @nmahale10 and @m0d00ku,

Sorry for the very late response. There was an error in the class hierarchy. It is fixed now, please follow the basic instructions. I hope you can build it successfully if you still need it. 

Dear @Delphi251189,

1. It is fixed now and I hope you can build it successfully. 
2. We have provided the basic instructions to build and run the code.
3. This was a course project we did three years ago. Its capabilities are limited. What it does is only converting ui file into an HTML file with bootstrap elements.  You can see the provided examples that the application can convert into HTML. If it cannot convert an element, it just skips the element. We are planning to extend the documentation with a list of its capabilities based on a mapping from ui components to HTML elements that converts. I hope the current version can help you.

**Comment by cankurtan** [comment]
It seems like compile problem is solved. I will close this issue.
